international_airports = {
    ('MAD', 'Adolfo Suárez Madrid–Barajas Airport', 'Madrid'),
    ('ATH', 'Eleftherios Venizelos Airport', 'Athens'),
    ('BNE', 'Brisbane Airport', 'Brisbane'),
    ('MUC', 'Munich Airport', 'Munich'),
    ('OSL', 'Oslo Airport', 'Oslo'),
    ('JED', 'King Abdulaziz International Airport', 'Jeddah'),
    ('ZRH', 'Zurich Airport', 'Zurich'),
    ('SVO', 'Sheremetyevo International Airport', 'Moscow'),
    ('GRU', 'São Paulo/Guarulhos–Governador André Franco Montoro International Airport', 'São Paulo'),
    ('LIM', 'Jorge Chávez International Airport', 'Lima'),
    ('HAM', 'Hamburg Airport', 'Hamburg'),
    ('BCN', 'Barcelona–El Prat Airport', 'Barcelona'),
    ('JNB', 'O.R. Tambo International Airport', 'Johannesburg'),
    ('HND', 'Haneda Airport', 'Tokyo'),
    ('DOH', 'Hamad International Airport', 'Doha'),
    ('BOM', 'Chhatrapati Shivaji Maharaj International Airport', 'Mumbai'),
    ('CGK', 'Soekarno–Hatta International Airport', 'Jakarta'),
    ('CDG', 'Charles de Gaulle Airport', 'Paris'),
    ('CPH', 'Copenhagen Airport', 'Copenhagen'),
    ('ICN', 'Incheon International Airport', 'Seoul'),
    ('LIS', 'Lisbon Portela Airport', 'Lisbon'),
    ('FRA', 'Frankfurt Airport', 'Frankfurt'),
    ('MNL', 'Ninoy Aquino International Airport',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'Manila'),
    ('DXB', 'Dubai International Airport', 'Dubai'),
    ('MEL', 'Melbourne Airport', 'Melbourne'),
    ('MIA', 'Miami International Airport', 'Miami'),
    ('HKG', 'Hong Kong International Airport', 'Hong Kong'),
    ('CAN', 'Guangzhou Baiyun International Airport', 'Guangzhou'),
    ('LHR', 'Heathrow Airport', 'London'),
    ('AUH', 'Abu Dhabi International Airport', 'Abu Dhabi'),
    ('MEX', 'Mexico City International Airport', 'Mexico City'),
    ('DEL', 'Indira Gandhi International Airport', 'New Delhi'),
    ('CPT', 'Cape Town International Airport', 'Cape Town'),
    ('SIN', 'Singapore Changi Airport', 'Singapore'),
    ('EZE', 'Ministro Pistarini International Airport', 'Buenos Aires'),
    ('IST', 'Istanbul Airport', 'Istanbul'),
    ('AKL', 'Auckland Airport', 'Auckland'),
    ('YYZ', 'Toronto Pearson International Airport', 'Toronto'),
    ('AMS', 'Amsterdam Airport Schiphol', 'Amsterdam'),
    ('DUB', 'Dublin Airport', 'Dublin'),
    ('HKD', 'Hong Kong International Airport', 'Hong Kong'),
    ('PEK', 'Beijing Capital International Airport', 'Beijing'),
    ('BRU', 'Brussels Airport', 'Brussels'),
    ('SYD', 'Sydney Kingsford Smith Airport', 'Sydney'),
    ('BKK', 'Suvarnabhumi Airport', 'Bangkok')
}

airlines = [
    'Emirates',
    'Delta Air Lines',
    'Qatar Airways',
    'Singapore Airlines',
    'Lufthansa',
    'American Airlines',
    'Air Canada',
    'British Airways',
    'ANA All Nippon Airways',
    'Cathay Pacific',
    'Etihad Airways',
    'Southwest Airlines',
    'Air France',
    'Turkish Airlines',
    'Qantas',
    'KLM Royal Dutch Airlines',
    'Virgin Atlantic',
    'United Airlines',
    'Alitalia',
    'Emirates',
    'Japan Airlines',
    'Finnair',
    'Swiss International Air Lines',
    'Aeroflot',
    'Iberia Airlines'
]
