international_airports = {
    ('LHR', 'Heathrow Airport', 'London'),
    ('CDG', 'Charles de Gaulle Airport', 'Paris'),
    ('HND', 'Haneda Airport', 'Tokyo'),
    ('DXB', 'Dubai International Airport', 'Dubai'),
    ('PEK', 'Beijing Capital International Airport', 'Beijing'),
    ('SYD', 'Sydney Kingsford Smith Airport', 'Sydney'),
    ('YYZ', 'Toronto Pearson International Airport', 'Toronto'),
    ('MEX', 'Mexico City International Airport', 'Mexico City'),
    ('AMS', 'Amsterdam Airport Schiphol', 'Amsterdam'),
    ('FRA', 'Frankfurt Airport', 'Frankfurt'),
    ('SIN', 'Singapore Changi Airport', 'Singapore'),
    ('ICN', 'Incheon International Airport', 'Seoul'),
    ('IST', 'Istanbul Airport', 'Istanbul'),
    ('MUC', 'Munich Airport', 'Munich'),
    ('HKD', 'Hong Kong International Airport', 'Hong Kong'),
    ('ZRH', 'Zurich Airport', 'Zurich'),
    ('SYD', 'Kingsford Smith Airport', 'Sydney'),
    ('BKK', 'Suvarnabhumi Airport', 'Bangkok'),
    ('MIA', 'Miami International Airport', 'Miami'),
    ('DEL', 'Indira Gandhi International Airport', 'New Delhi'),
    ('JNB', 'O.R. Tambo International Airport', 'Johannesburg'),
    ('SVO', 'Sheremetyevo International Airport', 'Moscow'),
    ('AUH', 'Abu Dhabi International Airport', 'Abu Dhabi'),
    ('GRU', 'São Paulo/Guarulhos–Governador André Franco Montoro International Airport', 'São Paulo'),
    ('YYZ', 'Toronto Pearson International Airport', 'Toronto'),
    ('CAN', 'Guangzhou Baiyun International Airport', 'Guangzhou'),
    ('MEL', 'Melbourne Airport', 'Melbourne'),
    ('LIS', 'Lisbon Portela Airport', 'Lisbon'),
    ('MAD', 'Adolfo Suárez Madrid–Barajas Airport', 'Madrid'),
    ('MNL', 'Ninoy Aquino International Airport', 'Manila'),
    ('CPT', 'Cape Town International Airport', 'Cape Town'),
    ('AMS', 'Amsterdam Airport Schiphol', 'Amsterdam'),
    ('ZRH', 'Zurich Airport', 'Zurich'),
    ('HKG', 'Hong Kong International Airport', 'Hong Kong'),
    ('LIM', 'Jorge Chávez International Airport', 'Lima'),
    ('AKL', 'Auckland Airport', 'Auckland'),
    ('CGK', 'Soekarno–Hatta International Airport', 'Jakarta'),
    ('BOM', 'Chhatrapati Shivaji Maharaj International Airport', 'Mumbai'),
    ('BRU', 'Brussels Airport', 'Brussels'),
    ('JED', 'King Abdulaziz International Airport', 'Jeddah'),
    ('ATH', 'Eleftherios Venizelos Airport', 'Athens'),
    ('CPH', 'Copenhagen Airport', 'Copenhagen'),
    ('DUB', 'Dublin Airport', 'Dublin'),
    ('OSL', 'Oslo Airport', 'Oslo'),
    ('HAM', 'Hamburg Airport', 'Hamburg'),
    ('SYD', 'Sydney Kingsford Smith Airport', 'Sydney'),
    ('MEX', 'Mexico City International Airport', 'Mexico City'),
    ('EZE', 'Ministro Pistarini International Airport', 'Buenos Aires'),
    ('BNE', 'Brisbane Airport', 'Brisbane'),
    ('LIS', 'Lisbon Portela Airport', 'Lisbon'),
    ('IST', 'Istanbul Airport', 'Istanbul'),
    ('MUC', 'Munich Airport', 'Munich'),
    ('DOH', 'Hamad International Airport', 'Doha'),
    ('BCN', 'Barcelona–El Prat Airport', 'Barcelona'),
    ('AMS', 'Amsterdam Airport Schiphol', 'Amsterdam'),
    ('IST', 'Istanbul Airport', 'Istanbul'),
    ('ZRH', 'Zurich Airport', 'Zurich'),
    ('MUC', 'Munich Airport', 'Munich'),
    ('HKG', 'Hong Kong International Airport', 'Hong Kong'),
    ('SVO', 'Sheremetyevo International Airport', 'Moscow'),
    ('DXB', 'Dubai International Airport', 'Dubai'),
    ('SYD', 'Sydney Kingsford Smith Airport', 'Sydney'),
    ('YYZ', 'Toronto Pearson International Airport', 'Toronto'),
    ('SIN', 'Singapore Changi Airport', 'Singapore'),
    ('ICN', 'Incheon International Airport', 'Seoul'),
    ('BKK', 'Suvarnabhumi Airport', 'Bangkok'),
    ('DEL', 'Indira Gandhi International Airport', 'New Delhi'),
    ('JNB', 'O.R. Tambo International Airport', 'Johannesburg'),
    ('SVO', 'Sheremetyevo International Airport', 'Moscow'),
    ('AUH', 'Abu Dhabi International Airport', 'Abu Dhabi'),
    ('GRU', 'São Paulo/Guarulhos–Governador André Franco Montoro International Airport', 'São Paulo'),
    ('YYZ', 'Toronto Pearson International Airport', 'Toronto'),
    ('CAN', 'Guangzhou Baiyun International Airport', 'Guangzhou'),
    ('MEL', 'Melbourne Airport', 'Melbourne'),
    ('LIS', 'Lisbon Portela Airport', 'Lisbon'),
    ('MAD', 'Adolfo Suárez Madrid–Barajas Airport', 'Madrid'),
    ('MNL', 'Ninoy Aquino International Airport', 'Manila'),
    ('CPT', 'Cape Town International Airport', 'Cape Town'),
    ('AMS', 'Amsterdam Airport Schiphol', 'Amsterdam'),
    ('ZRH', 'Zurich Airport', 'Zurich'),
    ('HKG', 'Hong Kong International Airport', 'Hong Kong'),
    ('LIM', 'Jorge Chávez International Airport', 'Lima'),
    ('AKL', 'Auckland Airport', 'Auckland'),
    ('CGK', 'Soekarno–Hatta International Airport', 'Jakarta'),
    ('BOM', 'Chhatrapati Shivaji Maharaj International Airport', 'Mumbai'),
    ('BRU', 'Brussels Airport', 'Brussels'),
    ('JED', 'King Abdulaziz International Airport', 'Jeddah'),
    ('ATH', 'Eleftherios Venizelos Airport', 'Athens'),
    ('CPH', 'Copenhagen Airport', 'Copenhagen'),
    ('DUB', 'Dublin Airport', 'Dublin'),
}

airlines = [
    'Emirates',
    'Delta Air Lines',
    'Qatar Airways',
    'Singapore Airlines',
    'Lufthansa',
    'American Airlines',
    'Air Canada',
    'British Airways',
    'ANA All Nippon Airways',
    'Cathay Pacific',
    'Etihad Airways',
    'Southwest Airlines',
    'Air France',
    'Turkish Airlines',
    'Qantas',
    'KLM Royal Dutch Airlines',
    'Virgin Atlantic',
    'United Airlines',
    'Alitalia',
    'Emirates',
    'Japan Airlines',
    'Finnair',
    'Swiss International Air Lines',
    'Aeroflot',
    'Iberia Airlines'
]